version: "3.7"

services:
  bot:
    build: bot/
    network_mode: host
    restart: always
    environment:
      TZ: Europe/Moscow
      DB_USER: #Имя пользователя
      DB_PASSWORD: #Пароль
      DB_HOST: #Host
      DB_BASE: #Имя базы даныых
      API_TOKEN: #TelegramBot Token
      GOOGLE_KEY: #key из таблицы google
      GOOGLE_TABLE_HALL: #key из таблицы google
      GOOGLE_JSON: #Навазние файла
      DELAY: #В минутах
    volumes:
      - /home/vestimy/project/notification_bot/bot:/usr/src/app/
    command: >
      sh -c "python bot.py"

volumes:
  db_volume: